/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import basiclibrary.lib.src.main.Library;
import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    
  @Test
    public void testRoll() {
        Library library = new Library();
        int[] rolls = library.roll(4);

        assertEquals(4, rolls.length);
        for (int roll : rolls) {
            assertTrue(roll >= 1 && roll <= 6);
        }
    }
        
    @Test
    public void testContainsDuplicatesOrNot() {   // testing duplicate method
        Library library = new Library();
        int[] arrWithDuplicates = {1, 2, 3,10, 6,55, 4, 5, 1};
        assertTrue(library.containsDuplicates(arrWithDuplicates));
    }

    @Test
    public void testCalculateAverage() {   // testing average calculation
        Library library = new Library();
        int[] numbers = {1, 2, 3, 4, 5, 3};
        double average = library.calculateAverage(numbers);
        assertEquals(3.0, average);
    }
    @Test
    public void testCalculateLowestAverage() {
        Library library = new Library();
        int[][] arrays = {
            {1, 2, 3},
            {4, 5, 6},
            {7, 8, 9}
        };
        int[] lowestAverageArray = library.calculateLowestAverage(arrays);
        assertArrayEquals(new int[]{1, 2, 3}, lowestAverageArray);
    }

    @Test
    public void analyzeWeatherData(){
        int[][] weeklyMonthTemperaturesSeattle = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        Library library = new Library();
        String analysisResult = Library.analyzeWeatherData(weeklyMonthTemperaturesSeattle);
        String expectedOutput = "High: 72\n" +
                "Low: 51\n" +
                "Never saw temperature: 63\n" +
                "Never saw temperature: 67\n" +
                "Never saw temperature: 68\n" +
                "Never saw temperature: 69\n";

        assertEquals(expectedOutput, analysisResult);
    }
    @Test
    public void testTally() {
        // Initialize a list of votes
        List<String> votes = Arrays.asList("Bush", "Bush", "Bush", "Shrub", "Hedge", "Shrub", "Bush", "Hedge", "Bush");

        // Call the method you want to test
        String result = Library.tally(votes);

        // Compare the result with the expected value using assertEquals
        assertEquals("Bush", result);
    }

}


