/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance.lib.src.main.java.inheritance;



public class Library {
   Restaurant restaurantOne= new Restaurant();
   Review reviewOne= new Review();
}
