/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter.app.src.main.java.linter;

import java.io.File;
import java.io.IOException;
import java.util.Scanner;

public class App {


    public static void main(String[] args) {
        File gatesFile = new File("linter/app/resources/gates.js");
        String errorMessage = findMissingSemicolons(gatesFile);

        if (errorMessage != null && !errorMessage.isEmpty()) {
            System.out.println("Errors found:");
            System.out.println(errorMessage);
        } else {
            System.out.println("No missing semicolons found.");
        }
    }

    public static String findMissingSemicolons(File filePath) {

        String errorMessage = null;  // or = " "
        try {
            Scanner scan = new Scanner(filePath);
            int lineNumber = 0;
            while (scan.hasNextLine()) {
                String line = scan.nextLine();
                lineNumber++;

                if (line.trim().isEmpty() ||
                        line.trim().endsWith("{") ||
                        line.trim().endsWith("}") ||
                        line.contains("if") ||
                        line.contains("else")) {
                    continue;
                }
                errorMessage = "";
                if (!line.trim().endsWith(";")) {
                    errorMessage += "Line " + lineNumber + ": Missing semicolon.\n";
                }
            }
        } catch (IOException e) {
            System.out.println(e);
        }

        return errorMessage;
    };
}
