/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.IOException;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static String findMissingSemicolons(File filePath) {

        String errorMessage = null;  // or = " "
        try {
            Scanner scan = new Scanner(filePath);
            int lineNumber = 0;
            while (scan.hasNextLine()) {
                String line = scan.nextLine();
                lineNumber++;

                if (line.trim().isEmpty() ||
                        line.trim().endsWith("{") ||
                        line.trim().endsWith("}") ||
                        line.contains("if") ||
                        line.contains("else")) {
                    continue;
                }
                errorMessage = "";
                if (!line.trim().endsWith(";")) {
                    errorMessage += "Line " + lineNumber + ": Missing semicolon.\n";
                }
            }
        } catch (IOException e) {
            System.out.println(e);
        }

        return errorMessage;
    };
}
