/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance.lib.src.test.java.inheritance;

import inheritance.lib.src.main.java.inheritance.Restaurant;
import inheritance.lib.src.main.java.inheritance.Review;
import inheritance.lib.src.main.java.inheritance.Shop;
import inheritance.lib.src.main.java.inheritance.Theater;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test
    void testRestaurantToString() {
        Restaurant restaurant = new Restaurant("Tasty Bites", 4, 3);
        String expected = "Restaurant{name='Tasty Bites', numberOfStars=4.0, price= 3'}";
        assertEquals(expected, restaurant.toString());
    }


    @Test
    void testReviewToString() {
        Restaurant restaurant = new Restaurant("Tasty Bites", 4, 3);
        Review review = new Review("Delicious food and great ambiance!", "John Doe", 5, restaurant);
        String expected = "Review{body='Delicious food and great ambiance!', author='John Doe', numberOfStars=5.0, Place=Tasty Bites}";
        assertEquals(expected, review.toString());
    }

    @Test
    void testRestaurantAndReview() {
        Restaurant restaurant = new Restaurant("Tasty Bites", 4, 3);
        Review review = new Review("Delicious food and great ambiance!", "John Doe", 5, restaurant);

        assertEquals("Tasty Bites", restaurant.getName());
        assertEquals("Restaurant{name='Tasty Bites', numberOfStars=4.0, price= 3'}\nReviews: [Review by John Doe\nStars: 5\nBody: Delicious food and great ambiance!\nAbout Restaurant: Tasty Bites]", restaurant.toString() + "\nReviews: [Review by John Doe\nStars: 5\nBody: Delicious food and great ambiance!\nAbout Restaurant: "+restaurant.getName() + "]");
    }

    @Test
    public void testShopConstructor() {
        Shop shop = new Shop("Fashion Haven", "Trendy clothes for all ages", 2);
        assertEquals("Fashion Haven", shop.getName());
        assertEquals("Trendy clothes for all ages", shop.getDescription());
        assertEquals(2, shop.getNumberOfDollarSigns());
    }
    @Test
    public void testReviewConstructorForShop() {
        Shop shop = new Shop("Fashion Haven", "Trendy clothes for all ages", 2);
        Review review = new Review("Great collection and friendly staff!", "Adam", 4, shop);
        assertEquals("Great collection and friendly staff!", review.getBody());
        assertEquals("Adam", review.getAuthor());
        assertEquals(4, review.getNumberOfStars());
    }
    @Test
    public void testReviewConstructorForTheater() {
        Theater theater = new Theater("Cineplex");
        Review review = new Review("Great cinema experience!", "Eva", 5, "Joker" , theater);
        assertEquals("Great cinema experience!", review.getBody());
        assertEquals("Eva", review.getAuthor());
        assertEquals(5, review.getNumberOfStars());
        assertEquals("Joker", review.getMovie());
    }

    @Test
    public void testTheaterConstructor() {
        Theater theater = new Theater("Abdali");
        assertEquals("Abdali", theater.getName());
        assertTrue(theater.getMovies().isEmpty());
    }
}
