/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance.lib.src.test.java.inheritance;

import inheritance.lib.src.main.java.inheritance.Restaurant;
import inheritance.lib.src.main.java.inheritance.Review;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test
    void testRestaurantToString() {
        Restaurant restaurant = new Restaurant("Tasty Bites", 4, 3);
        String expected = "Restaurant{name='Tasty Bites', numberOfStars=4, price= 3'}";
        assertEquals(expected, restaurant.toString());
    }


    @Test
    void testReviewToString() {
        Review review = new Review("Delicious food and great ambiance!", "John Doe", 5);
        String expected = "Review{body='Delicious food and great ambiance!', author='John Doe', numberOfStars=5}";
        assertEquals(expected, review.toString());
    }

    @Test
    void testRestaurantAndReview() {
        Restaurant restaurant = new Restaurant("Tasty Bites", 4, 3);
        Review review = new Review("Delicious food and great ambiance!", "John Doe", 5, restaurant);

        assertEquals("Tasty Bites", restaurant.getName());
        assertEquals("Restaurant{name='Tasty Bites', numberOfStars=5, price= 3'}\nReviews: [Review by John Doe\nStars: 5\nBody: Delicious food and great ambiance!\nAbout Restaurant: Tasty Bites]", restaurant.toString() + "\nReviews: [Review by John Doe\nStars: 5\nBody: Delicious food and great ambiance!\nAbout Restaurant: "+restaurant.getName() + "]");
    }
}
